// <auto-generated />
using System;
using GestionCompetences.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionCompetences.Infrastructure.Migrations
{
    [DbContext(typeof(CompetenceDBContext))]
    partial class CompetenceDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionCompetences.Entitie.Competence.Categorie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Categorie", (string)null);
                });

            modelBuilder.Entity("GestionCompetences.Entitie.Competence.CertificatObtenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeCertificat")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("DateObtention")
                        .HasColumnType("datetime2");

                    b.Property<string>("Editeur")
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("NomCertificat")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(150)");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Certificat_obtenue", null, t =>
                        {
                            t.HasCheckConstraint("CK_CertificatObtenue_Date", "YEAR(DateObtention) >= 2000");
                        });
                });

            modelBuilder.Entity("GestionCompetences.Entitie.Competence.CompetenceUtilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategorieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CertificatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateDeDebut")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lien")
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<Guid>("NiveauId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(150)");

                    b.Property<string>("NomGroupe")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(150)");

                    b.Property<string>("Note")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Visibilite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("CertificatId");

                    b.HasIndex("NiveauId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Competence_Utilisateur", null, t =>
                        {
                            t.HasCheckConstraint("CK_CompetenceU", "Position > 0");
                        });
                });

            modelBuilder.Entity("GestionCompetences.Entitie.Competence.HistoriqueProgression", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AncienNiveauId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NouveauNiveauId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AncienNiveauId");

                    b.HasIndex("CompetenceId");

                    b.HasIndex("NouveauNiveauId");

                    b.ToTable("Historique_Progression", (string)null);
                });

            modelBuilder.Entity("GestionCompetences.Entitie.Competence.NiveauCompetence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)");

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.ToTable("Niveau_competence", (string)null);
                });

            modelBuilder.Entity("GestionCompetences.Entitie.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(150)");

                    b.Property<bool>("EstActif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(150)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(150)");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilisateur", (string)null);
                });

            modelBuilder.Entity("GestionCompetences.Entitie.Competence.CertificatObtenu", b =>
                {
                    b.HasOne("GestionCompetences.Entitie.Utilisateur", "Utilisateur")
                        .WithMany("CertificatsObtenus")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("GestionCompetences.Entitie.Competence.CompetenceUtilisateur", b =>
                {
                    b.HasOne("GestionCompetences.Entitie.Competence.Categorie", "Categorie")
                        .WithMany("CompetencesListe")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionCompetences.Entitie.Competence.CertificatObtenu", "CertificatObtenu")
                        .WithMany("CompetencesLsite")
                        .HasForeignKey("CertificatId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestionCompetences.Entitie.Competence.NiveauCompetence", "Niveau")
                        .WithMany("CompetenceListe")
                        .HasForeignKey("NiveauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionCompetences.Entitie.Utilisateur", "Utilisateur")
                        .WithMany("Competences")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("CertificatObtenu");

                    b.Navigation("Niveau");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("GestionCompetences.Entitie.Competence.HistoriqueProgression", b =>
                {
                    b.HasOne("GestionCompetences.Entitie.Competence.NiveauCompetence", "AncienNiveau")
                        .WithMany()
                        .HasForeignKey("AncienNiveauId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestionCompetences.Entitie.Competence.CompetenceUtilisateur", "Competence")
                        .WithMany("Historiques")
                        .HasForeignKey("CompetenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionCompetences.Entitie.Competence.NiveauCompetence", "NouveauNiveau")
                        .WithMany("Historiques")
                        .HasForeignKey("NouveauNiveauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AncienNiveau");

                    b.Navigation("Competence");

                    b.Navigation("NouveauNiveau");
                });

            modelBuilder.Entity("GestionCompetences.Entitie.Competence.Categorie", b =>
                {
                    b.Navigation("CompetencesListe");
                });

            modelBuilder.Entity("GestionCompetences.Entitie.Competence.CertificatObtenu", b =>
                {
                    b.Navigation("CompetencesLsite");
                });

            modelBuilder.Entity("GestionCompetences.Entitie.Competence.CompetenceUtilisateur", b =>
                {
                    b.Navigation("Historiques");
                });

            modelBuilder.Entity("GestionCompetences.Entitie.Competence.NiveauCompetence", b =>
                {
                    b.Navigation("CompetenceListe");

                    b.Navigation("Historiques");
                });

            modelBuilder.Entity("GestionCompetences.Entitie.Utilisateur", b =>
                {
                    b.Navigation("CertificatsObtenus");

                    b.Navigation("Competences");
                });
#pragma warning restore 612, 618
        }
    }
}
